language: java

stages:
  #- Test
  - VM

jobs:
  include:
    #- stage : Test
    #  script:
    #    - mvn test

    - stage: VM
      if: type != pull_request AND(branch = master OR branch = development)
      language: java
      before_script:
      - 'if [ "${TRAVIS_BRANCH}" = "development" ]; then
        export CONTAINER_TAG=develop;
        elif [ "${TRAVIS_BRANCH}" = "master" ]; then
        export CONTAINER_TAG=latest;'
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t mvjatos/seal-test:${CONTAINER_TAG} ConfMngr
        - docker push mvjatos/seal-test:${CONTAINER_TAG}